spring.application.name=hotels

server.port=8092
server.servlet.context-path=/property-view

# H2 DataSource
spring.datasource.url=jdbc:h2:mem:hotelsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
